### ISSUE TITLE
Problem with compiling

### ISSUE THREAD

**Issue by robsy** [OpenDTU-App/opendtu-react-native#258]
Hi,

I'm using opendtu-react-native for some weeks, and yes it's a very nice tool.
One function is missing for me:
Graphs are only shown for the voltage of each sting, but the voltage is not so interesting, because of the the integrated MPPT, at my site it's always ~35V for each sting. The current and power alters during the day and weather. 

I have never programmed/improved an android app, but programmed professionally some embedded devices on a very low level. Nevertheless, I believe that I can introduce the feature into the app.

So I forked  the develop tree, cloned it to my local system (Ubuntu) and wanted to build the (unchanged) app by executing "gradlew" inside the android folder. This was only to test the "toolchain", next step will be the integration of my idea.

The output of gradlew was: 
....
_FAILURE: Build failed with an exception._

_* Where:_
_Settings file '/home/.../AndroidStudioProjects/opendtu-react-native/android/settings.gradle' line: 2_

_* What went wrong:_
_Error resolving plugin [id: 'com.facebook.react.settings']_
\> _Included build '/home/.../AndroidStudioProjects/opendtu-react-native/node_modules/@react-native/gradle-plugin' does not exist._

....

I asked google for several hours and tried many things, but whatever I did, there was no change at all of this failure.

So my questions:
- Is it correct to build the android app by executing gradlew?
- Has anybody an idea howto solve this issue?
- Whats the original build system and version (linux or windows)

Thanks 

Robert

**Comment by CommanderRedYT** [comment]
Hi!

First of all, thank you! I think it's awesome that you want to contribute, if there is any way I can help, just hmu!

Because react-native is based around JavaScript, you first have to install NodeJS and download the modules.

Installing the modules can be done quite easily by running the command "yarn".

In general I would recommend to take a look at this file here: https://github.com/OpenDTU-App/opendtu-react-native/blob/develop/.github/workflows/pull-requests.yml

Also, here is a link to the react-native documentation: https://reactnative.dev/docs/set-up-your-environment

**Comment by robsy** [comment]
Hi, 

thanks for help. 
My solution:
- remove all Ubuntu-packages for yarn and android-sdk (or better android*)  
- clean up (means: deleted) all folders with *android* at my home-directory
- Installed yarn and android-studio by snap
- check out project again from github
- start yarn at project directory
- start android-studio and open project
- menu file - Settings - Build,Execution,Deployment - Build Tools - Grandle - Grandle JDK : **select** Temurin -17

Now the compile works and get an apk file.

Thanks a lot
